// Ánh xạ vai trò → danh sách quyền mặc định
// super_admin nhận tất cả quyền, các vai trò khác nhận tập con phù hợp

import { ALL_PERMISSIONS, PERMISSIONS, type Permission } from './permission-definitions'
import type { DemoRole } from '@/lib/demo/demo-accounts'

export type AppRole = DemoRole

// ── Module permissions mặc định theo vai trò ──────────────────────────────────

// Modules chung cho tất cả (dashboard, profile, settings)
const COMMON_MODULES: Permission[] = [
  PERMISSIONS.MODULE_DASHBOARD,
  PERMISSIONS.MODULE_PROFILE,
  PERMISSIONS.MODULE_SETTINGS,
]

// Modules dành cho thành viên (citizen)
const CITIZEN_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_MEMBERSHIP,
  PERMISSIONS.MODULE_FAMILY,
  PERMISSIONS.MODULE_UPLOAD,
  PERMISSIONS.MODULE_TIMELINE,
  PERMISSIONS.MODULE_SUMMARY,
  PERMISSIONS.MODULE_VISIT_PREP,
  PERMISSIONS.MODULE_TREATMENT,
  PERMISSIONS.MODULE_CHOOSE_DOCTOR,
  PERMISSIONS.MODULE_BOOK_APPOINTMENT,
  PERMISSIONS.MODULE_MESSAGES,
  PERMISSIONS.MODULE_FEEDBACK,
]

// Modules dành cho bác sĩ
const DOCTOR_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_DOCTOR_REGISTER,
  PERMISSIONS.MODULE_DOCTOR_PROFILE,
  PERMISSIONS.MODULE_DOCTOR_REVIEW,
  PERMISSIONS.MODULE_DOCTOR_SCHEDULE,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho BS chuyên khoa
const SPECIALIST_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_DOCTOR_REVIEW,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho BS khám bệnh
const EXAM_DOCTOR_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_EXAM_SCHEDULE,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho tiếp đón
const RECEPTION_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_RECEPTION,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho admin
const ADMIN_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_ADMIN,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho giám đốc
const DIRECTOR_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_ADMIN,
  PERMISSIONS.MODULE_DIRECTOR,
  PERMISSIONS.MODULE_PERMISSIONS,
  PERMISSIONS.MODULE_MESSAGES,
  PERMISSIONS.MODULE_TASK_ASSIGNMENT,
]

// Modules dành cho GĐ chi nhánh
const BRANCH_DIRECTOR_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_ADMIN,
  PERMISSIONS.MODULE_DIRECTOR,
  PERMISSIONS.MODULE_PERMISSIONS,
  PERMISSIONS.MODULE_MESSAGES,
  PERMISSIONS.MODULE_TASK_ASSIGNMENT,
]

// Modules dành cho nhân viên chung
const STAFF_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho kế toán
const ACCOUNTANT_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho hành chính (admin_staff)
const ADMIN_STAFF_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho quản lý (manager)
const MANAGER_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_ADMIN,
  PERMISSIONS.MODULE_MESSAGES,
  PERMISSIONS.MODULE_TASK_ASSIGNMENT,
]

// Modules dành cho kỹ thuật (technician, tech_assistant, nurse, support_staff, intern)
const BASIC_STAFF_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_MESSAGES,
]

// Modules dành cho khách
const GUEST_MODULES: Permission[] = [
  ...COMMON_MODULES,
  PERMISSIONS.MODULE_REGISTER_MEMBER,
]

// Quyền của director (toàn quyền trừ cài đặt hệ thống)
const DIRECTOR_PERMISSIONS: Permission[] = ALL_PERMISSIONS.filter(
  (p) => p !== PERMISSIONS.SETTINGS_EDIT_SYSTEM
)

// Quyền của branch_director (chỉ trong phạm vi chi nhánh)
const BRANCH_DIRECTOR_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_EDIT,
  PERMISSIONS.MEMBERS_APPROVE,
  PERMISSIONS.MEMBERS_SUSPEND,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_SEND_GROUP,
  PERMISSIONS.ANNOUNCEMENTS_SEND_INDIVIDUAL,
  PERMISSIONS.BRANCHES_VIEW,
  PERMISSIONS.BRANCHES_EDIT,
  PERMISSIONS.BRANCHES_ASSIGN_STAFF,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_ACCEPT,
  PERMISSIONS.EXAM_REGISTRATION_ASSIGN_DOCTOR,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_EDIT_BRANCH,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_CONFIRM,
  ...BRANCH_DIRECTOR_MODULES,
]

// Quyền của admin (quản lý thành viên, thông báo, nhật ký — KHÔNG phân quyền)
const ADMIN_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_CREATE,
  PERMISSIONS.MEMBERS_EDIT,
  PERMISSIONS.MEMBERS_DELETE,
  PERMISSIONS.MEMBERS_APPROVE,
  PERMISSIONS.MEMBERS_SUSPEND,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_DELETE,
  PERMISSIONS.ANNOUNCEMENTS_SEND_ALL,
  PERMISSIONS.ANNOUNCEMENTS_SEND_GROUP,
  PERMISSIONS.ANNOUNCEMENTS_SEND_INDIVIDUAL,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.PAYMENTS_VIEW,
  ...ADMIN_MODULES,
]

// Quyền của doctor (xem hồ sơ BN được gán, quản lý lịch)
const DOCTOR_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_ASSIGNED,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_COMPLETE,
  PERMISSIONS.SETTINGS_VIEW,
  ...DOCTOR_MODULES,
]

// Quyền của specialist (BS chuyên khoa — giống doctor + xem hồ sơ BN chuyển tuyến)
const SPECIALIST_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_ASSIGNED,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_COMPLETE,
  PERMISSIONS.SETTINGS_VIEW,
  ...SPECIALIST_MODULES,
]

// Quyền của exam_doctor (bác sĩ khám bệnh)
const EXAM_DOCTOR_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_ASSIGNED,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_ACCEPT,
  PERMISSIONS.EXAM_REGISTRATION_COMPLETE,
  PERMISSIONS.SETTINGS_VIEW,
  ...EXAM_DOCTOR_MODULES,
]

// Quyền của reception (tiếp đón — xem + tạo thành viên, tiếp nhận khám)
const RECEPTION_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_CREATE,
  PERMISSIONS.MEMBERS_APPROVE,
  PERMISSIONS.EXAM_REGISTRATION_CREATE,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_ACCEPT,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_CONFIRM,
  PERMISSIONS.SETTINGS_VIEW,
  ...RECEPTION_MODULES,
]

// Quyền của staff (nhân viên)
const STAFF_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
  ...STAFF_MODULES,
]

// Quyền của accountant (kế toán)
const ACCOUNTANT_PERMISSIONS: Permission[] = [
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_CONFIRM,
  PERMISSIONS.PAYMENTS_EXPORT,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
  ...ACCOUNTANT_MODULES,
]

// Quyền của admin_staff (hành chính — trước đây là hr)
const ADMIN_STAFF_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_CREATE,
  PERMISSIONS.MEMBERS_EDIT,
  PERMISSIONS.BRANCHES_VIEW,
  PERMISSIONS.BRANCHES_ASSIGN_STAFF,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.SETTINGS_VIEW,
  ...ADMIN_STAFF_MODULES,
]

// Quyền của manager (quản lý — tương tự branch_director, không có branch management)
const MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.SETTINGS_VIEW,
  ...MANAGER_MODULES,
]

// Quyền của technician (kỹ thuật)
const TECHNICIAN_PERMISSIONS: Permission[] = [
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_EDIT_SYSTEM,
  ...BASIC_STAFF_MODULES,
]

// Quyền của tech_assistant (kỹ thuật viên)
const TECH_ASSISTANT_PERMISSIONS: Permission[] = [
  PERMISSIONS.SETTINGS_VIEW,
  ...BASIC_STAFF_MODULES,
]

// Quyền của nurse (điều dưỡng)
const NURSE_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_ASSIGNED,
  PERMISSIONS.SETTINGS_VIEW,
  ...BASIC_STAFF_MODULES,
]

// Quyền của support_staff (nhân viên hỗ trợ)
const SUPPORT_STAFF_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
  ...BASIC_STAFF_MODULES,
]

// Quyền của intern (nhân viên thực tập — tối thiểu)
const INTERN_PERMISSIONS: Permission[] = [
  PERMISSIONS.SETTINGS_VIEW,
  ...BASIC_STAFF_MODULES,
]

// Quyền của citizen (thành viên)
const CITIZEN_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_OWN,
  PERMISSIONS.HEALTH_RECORDS_VIEW_FAMILY,
  PERMISSIONS.EXAM_REGISTRATION_CREATE,
  PERMISSIONS.SETTINGS_VIEW,
  ...CITIZEN_MODULES,
]

// Quyền của guest (khách)
const GUEST_PERMISSIONS: Permission[] = [
  ...GUEST_MODULES,
]

export const ROLE_DEFAULT_PERMISSIONS: Record<AppRole, Permission[]> = {
  super_admin: ALL_PERMISSIONS,
  director: DIRECTOR_PERMISSIONS,
  branch_director: BRANCH_DIRECTOR_PERMISSIONS,
  admin: ADMIN_PERMISSIONS,
  doctor: DOCTOR_PERMISSIONS,
  specialist: SPECIALIST_PERMISSIONS,
  exam_doctor: EXAM_DOCTOR_PERMISSIONS,
  reception: RECEPTION_PERMISSIONS,
  staff: STAFF_PERMISSIONS,
  accountant: ACCOUNTANT_PERMISSIONS,
  admin_staff: ADMIN_STAFF_PERMISSIONS,
  manager: MANAGER_PERMISSIONS,
  technician: TECHNICIAN_PERMISSIONS,
  tech_assistant: TECH_ASSISTANT_PERMISSIONS,
  nurse: NURSE_PERMISSIONS,
  support_staff: SUPPORT_STAFF_PERMISSIONS,
  intern: INTERN_PERMISSIONS,
  citizen: CITIZEN_PERMISSIONS,
  guest: GUEST_PERMISSIONS,
}

/** Lấy quyền mặc định theo vai trò */
export function getDefaultPermissions(role: string): Permission[] {
  return ROLE_DEFAULT_PERMISSIONS[role as AppRole] ?? GUEST_PERMISSIONS
}
