// Ánh xạ vai trò → danh sách quyền mặc định
// super_admin nhận tất cả quyền, các vai trò khác nhận tập con phù hợp

import { ALL_PERMISSIONS, PERMISSIONS, type Permission } from './permission-definitions'
import type { DemoRole } from '@/lib/demo/demo-accounts'

export type AppRole = DemoRole

// Quyền của director (toàn quyền trừ cài đặt hệ thống)
const DIRECTOR_PERMISSIONS: Permission[] = ALL_PERMISSIONS.filter(
  (p) => p !== PERMISSIONS.SETTINGS_EDIT_SYSTEM
)

// Quyền của branch_director (chỉ trong phạm vi chi nhánh)
const BRANCH_DIRECTOR_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_EDIT,
  PERMISSIONS.MEMBERS_APPROVE,
  PERMISSIONS.MEMBERS_SUSPEND,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_SEND_GROUP,
  PERMISSIONS.ANNOUNCEMENTS_SEND_INDIVIDUAL,
  PERMISSIONS.BRANCHES_VIEW,
  PERMISSIONS.BRANCHES_EDIT,
  PERMISSIONS.BRANCHES_ASSIGN_STAFF,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_ACCEPT,
  PERMISSIONS.EXAM_REGISTRATION_ASSIGN_DOCTOR,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_EDIT_BRANCH,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_CONFIRM,
]

// Quyền của admin (quản lý thành viên, thông báo, nhật ký — KHÔNG phân quyền)
const ADMIN_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_CREATE,
  PERMISSIONS.MEMBERS_EDIT,
  PERMISSIONS.MEMBERS_DELETE,
  PERMISSIONS.MEMBERS_APPROVE,
  PERMISSIONS.MEMBERS_SUSPEND,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_EDIT,
  PERMISSIONS.ANNOUNCEMENTS_DELETE,
  PERMISSIONS.ANNOUNCEMENTS_SEND_GROUP,
  PERMISSIONS.ANNOUNCEMENTS_SEND_INDIVIDUAL,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.PAYMENTS_VIEW,
]

// Quyền của doctor (xem hồ sơ BN được gán, quản lý lịch)
const DOCTOR_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_ASSIGNED,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_COMPLETE,
  PERMISSIONS.SETTINGS_VIEW,
]

// Quyền của exam_doctor (bác sĩ khám bệnh)
const EXAM_DOCTOR_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_ASSIGNED,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_ACCEPT,
  PERMISSIONS.EXAM_REGISTRATION_COMPLETE,
  PERMISSIONS.SETTINGS_VIEW,
]

// Quyền của reception (tiếp đón)
const RECEPTION_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.EXAM_REGISTRATION_CREATE,
  PERMISSIONS.EXAM_REGISTRATION_REVIEW,
  PERMISSIONS.EXAM_REGISTRATION_ACCEPT,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_CONFIRM,
  PERMISSIONS.SETTINGS_VIEW,
]

// Quyền của staff (nhân viên)
const STAFF_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.ANNOUNCEMENTS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
]

// Quyền của accountant (kế toán)
const ACCOUNTANT_PERMISSIONS: Permission[] = [
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_CONFIRM,
  PERMISSIONS.PAYMENTS_EXPORT,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.SETTINGS_VIEW,
]

// Quyền của hr (nhân sự/hành chính)
const HR_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBERS_VIEW,
  PERMISSIONS.MEMBERS_CREATE,
  PERMISSIONS.MEMBERS_EDIT,
  PERMISSIONS.BRANCHES_VIEW,
  PERMISSIONS.BRANCHES_ASSIGN_STAFF,
  PERMISSIONS.REPORTS_VIEW_BRANCH,
  PERMISSIONS.SETTINGS_VIEW,
]

// Quyền của citizen (thành viên)
const CITIZEN_PERMISSIONS: Permission[] = [
  PERMISSIONS.HEALTH_RECORDS_VIEW_OWN,
  PERMISSIONS.HEALTH_RECORDS_VIEW_FAMILY,
  PERMISSIONS.EXAM_REGISTRATION_CREATE,
  PERMISSIONS.SETTINGS_VIEW,
]

// Quyền của guest (khách)
const GUEST_PERMISSIONS: Permission[] = []

export const ROLE_DEFAULT_PERMISSIONS: Record<AppRole, Permission[]> = {
  super_admin: ALL_PERMISSIONS,
  director: DIRECTOR_PERMISSIONS,
  branch_director: BRANCH_DIRECTOR_PERMISSIONS,
  admin: ADMIN_PERMISSIONS,
  doctor: DOCTOR_PERMISSIONS,
  exam_doctor: EXAM_DOCTOR_PERMISSIONS,
  reception: RECEPTION_PERMISSIONS,
  staff: STAFF_PERMISSIONS,
  accountant: ACCOUNTANT_PERMISSIONS,
  hr: HR_PERMISSIONS,
  citizen: CITIZEN_PERMISSIONS,
  guest: GUEST_PERMISSIONS,
}

/** Lấy quyền mặc định theo vai trò */
export function getDefaultPermissions(role: string): Permission[] {
  return ROLE_DEFAULT_PERMISSIONS[role as AppRole] ?? GUEST_PERMISSIONS
}
